import Link from 'next/link';
import { ArrowRight, Building2, ChevronRight, FlaskConical, HeartHandshake, Home, MapPin, MessageCircle, ShieldCheck } from 'lucide-react';
import { ACTIVE_SERVICES } from '@/data/services';
import { FAQS } from '@/data/faqs';
import { BUSINESS } from '@/data/business';
import { BranchDetails, SectionHeading, WhatsAppLink } from '@/components/ui';
import { formatEstimatedPrice } from '@/lib/format';

const quickLinks = [
  { label: 'Exámenes y preparación', href: '/examenes/', icon: FlaskConical },
  { label: 'Toma de muestras a domicilio', href: '/atencion-domicilio-quito/', icon: Home },
  { label: 'Horarios y cómo llegar', href: '/sucursal/', icon: MapPin },
];

export default function HomePage() {
  return <>
    <section className="original-hero"><div className="container original-hero-grid"><div><div className="location-pill"><MapPin size={17} />Sector El Inca, Quito</div><h1>Exámenes de laboratorio con orientación clara y atención cercana</h1><p>Consulte preparación, valores estimados y atención a domicilio. Confirmaremos las condiciones de su solicitud por WhatsApp.</p><div className="hero-actions"><WhatsAppLink message="Hola, deseo consultar un examen y conocer su preparación, valor y disponibilidad." className="button hero-whatsapp">Consultar por WhatsApp</WhatsAppLink><Link className="button hero-outline" href="/atencion-domicilio-quito/">Solicitar domicilio <ArrowRight size={19} /></Link></div></div><div className="hero-consult-card"><div className="consult-card-inner"><div className="consult-card-heading"><div><p>Atención sencilla</p><h2>¿Qué necesita consultar?</h2></div><span><HeartHandshake size={24} /></span></div><div className="quick-links">{quickLinks.map(({ label, href, icon: Icon }) => <Link key={href} href={href}><span><Icon size={21} />{label}</span><ChevronRight size={18} /></Link>)}</div></div></div></div></section>
    <section className="trust-strip"><div className="container trust-grid"><article><MessageCircle size={23} /><div><h3>Consulta directa</h3><p>Continúe su consulta por WhatsApp con la información que necesita.</p></div></article><article><ShieldCheck size={23} /><div><h3>Información responsable</h3><p>Confirme requisitos, disponibilidad y valores antes de acudir.</p></div></article><article><Building2 size={23} /><div><h3>Atención en Quito</h3><p>Visite nuestra sucursal o coordine una toma de muestras a domicilio.</p></div></article></div></section>
    <section className="section catalogue-preview"><div className="container"><SectionHeading eyebrow="Exámenes y servicios" title="Encuentre el examen que necesita"><span>Revise valores estimados y confirme la preparación y cotización final por WhatsApp.</span></SectionHeading><div className="service-grid">{ACTIVE_SERVICES.slice(0, 6).map((service) => <article className="service-card" key={service.slug}><div className="service-card-top"><span className="service-category">{service.category}</span><p className="price">{formatEstimatedPrice(service.estimatedPrice)}</p></div><h3><Link href={`/examenes/${service.slug}/`}>{service.name}</Link></h3><p className="muted">{service.preparation}</p><div className="card-actions"><Link className="add-service" href="/examenes/">Agregar</Link><WhatsAppLink message={`Hola, quisiera consultar el examen ${service.name}.`} className="consult-service">Consultar</WhatsAppLink></div></article>)}</div><Link className="button primary-action section-action" href="/examenes/">Ver todo el catálogo <ArrowRight size={18} /></Link></div></section>
    <section className="section home-service-preview"><div className="container two-column"><div><SectionHeading eyebrow="Atención a domicilio" title="Solicite revisión para una toma de muestras en casa" align="left"><span>Comparta los datos iniciales y coordinaremos cobertura, fecha y preparación por WhatsApp.</span></SectionHeading><ol className="numbered-steps"><li>Indique los exámenes que necesita.</li><li>Comparta su sector o dirección y una fecha preferida.</li><li>Espere la confirmación de disponibilidad.</li></ol></div><div className="coverage-note"><MapPin size={22} /><h3>Cobertura</h3><p>{BUSINESS.homeCoverage}</p><Link href="/atencion-domicilio-quito/">Solicitar a domicilio <ArrowRight size={18} /></Link></div></div></section>
    <section className="section company-preview"><div className="container company-grid"><div><SectionHeading eyebrow="Empresas" title="Coordinación de servicios para salud ocupacional" align="left"><span>Cuéntenos el número de colaboradores, los exámenes requeridos, la ubicación y la fecha tentativa.</span></SectionHeading><Link className="button hero-whatsapp" href="/salud-ocupacional-empresas/">Solicitar cotización empresarial</Link></div><div className="company-feature-grid"><article><Building2 size={25} /><h3>Solicitud estructurada</h3><p>Recopile los datos clave antes de cotizar.</p></article><article><MapPin size={25} /><h3>Coordinación</h3><p>Fecha y disponibilidad revisadas para su solicitud.</p></article><article><ShieldCheck size={25} /><h3>Confidencialidad</h3><p>Tratamiento cuidadoso de los datos compartidos.</p></article><article><FlaskConical size={25} /><h3>Alcance claro</h3><p>Sin inventar perfiles ni requisitos clínicos.</p></article></div></div></section>
    <section className="section home-location-section"><div className="container"><SectionHeading eyebrow="Sucursal" title="Visítenos en el sector El Inca"><span>Encuentre dirección, horarios y el acceso directo para llegar o confirmar una consulta.</span></SectionHeading><BranchDetails /></div></section>
    <section className="section home-faq-section"><div className="container home-faq-container"><SectionHeading eyebrow="Preguntas frecuentes" title="Respuestas claras antes de su visita"><span>Lo esencial antes de coordinar un examen, acudir a la sucursal o solicitar atención a domicilio.</span></SectionHeading><div className="home-faq-card"><div className="faq-list">{FAQS.slice(0, 3).map((faq, index) => <details key={faq.question} open={index === 0}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div><div className="home-faq-footer"><p>¿Tiene otra consulta? Escríbanos con el examen o servicio que necesita.</p><Link className="button button-secondary" href="/preguntas-frecuentes/">Ver todas las preguntas <ArrowRight size={18} /></Link></div></div></div></section>
  </>;
}
